apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: changeme_root_password
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpressuser
  MYSQL_PASSWORD: changeme_wordpress_password
